// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v3.19.4
// source: common/v1/qiniu.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UpTokenRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpTokenRequest) Reset() {
	*x = UpTokenRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_v1_qiniu_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpTokenRequest) ProtoMessage() {}

func (x *UpTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_common_v1_qiniu_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpTokenRequest.ProtoReflect.Descriptor instead.
func (*UpTokenRequest) Descriptor() ([]byte, []int) {
	return file_common_v1_qiniu_proto_rawDescGZIP(), []int{0}
}

type UpTokenRequestReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
}

func (x *UpTokenRequestReply) Reset() {
	*x = UpTokenRequestReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_v1_qiniu_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpTokenRequestReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpTokenRequestReply) ProtoMessage() {}

func (x *UpTokenRequestReply) ProtoReflect() protoreflect.Message {
	mi := &file_common_v1_qiniu_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpTokenRequestReply.ProtoReflect.Descriptor instead.
func (*UpTokenRequestReply) Descriptor() ([]byte, []int) {
	return file_common_v1_qiniu_proto_rawDescGZIP(), []int{1}
}

func (x *UpTokenRequestReply) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type UploadFileBaseRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	File string `protobuf:"bytes,1,opt,name=file,proto3" json:"file,omitempty"`
	Path string `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
}

func (x *UploadFileBaseRequest) Reset() {
	*x = UploadFileBaseRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_v1_qiniu_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UploadFileBaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadFileBaseRequest) ProtoMessage() {}

func (x *UploadFileBaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_common_v1_qiniu_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadFileBaseRequest.ProtoReflect.Descriptor instead.
func (*UploadFileBaseRequest) Descriptor() ([]byte, []int) {
	return file_common_v1_qiniu_proto_rawDescGZIP(), []int{2}
}

func (x *UploadFileBaseRequest) GetFile() string {
	if x != nil {
		return x.File
	}
	return ""
}

func (x *UploadFileBaseRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type UploadFileBaseReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	File string `protobuf:"bytes,1,opt,name=file,proto3" json:"file,omitempty"`
}

func (x *UploadFileBaseReply) Reset() {
	*x = UploadFileBaseReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_v1_qiniu_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UploadFileBaseReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadFileBaseReply) ProtoMessage() {}

func (x *UploadFileBaseReply) ProtoReflect() protoreflect.Message {
	mi := &file_common_v1_qiniu_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadFileBaseReply.ProtoReflect.Descriptor instead.
func (*UploadFileBaseReply) Descriptor() ([]byte, []int) {
	return file_common_v1_qiniu_proto_rawDescGZIP(), []int{3}
}

func (x *UploadFileBaseReply) GetFile() string {
	if x != nil {
		return x.File
	}
	return ""
}

var File_common_v1_qiniu_proto protoreflect.FileDescriptor

var file_common_v1_qiniu_proto_rawDesc = []byte{
	0x0a, 0x15, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x76, 0x31, 0x2f, 0x71, 0x69, 0x6e, 0x69,
	0x75, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0d, 0x61, 0x70, 0x69, 0x2e, 0x75, 0x70, 0x6c,
	0x6f, 0x61, 0x64, 0x2e, 0x76, 0x31, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61,
	0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0x10, 0x0a, 0x0e, 0x55, 0x70, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x2b, 0x0a, 0x13, 0x55, 0x70, 0x54, 0x6f, 0x6b, 0x65,
	0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x14, 0x0a,
	0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f,
	0x6b, 0x65, 0x6e, 0x22, 0x3f, 0x0a, 0x15, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x46, 0x69, 0x6c,
	0x65, 0x42, 0x61, 0x73, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04,
	0x66, 0x69, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x66, 0x69, 0x6c, 0x65,
	0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x74, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x70, 0x61, 0x74, 0x68, 0x22, 0x29, 0x0a, 0x13, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x46, 0x69,
	0x6c, 0x65, 0x42, 0x61, 0x73, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x66,
	0x69, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x66, 0x69, 0x6c, 0x65, 0x32,
	0xfd, 0x01, 0x0a, 0x05, 0x51, 0x69, 0x4e, 0x69, 0x75, 0x12, 0x6e, 0x0a, 0x07, 0x55, 0x70, 0x54,
	0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x1d, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x75, 0x70, 0x6c, 0x6f, 0x61,
	0x64, 0x2e, 0x76, 0x31, 0x2e, 0x55, 0x70, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x22, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x75, 0x70, 0x6c, 0x6f, 0x61, 0x64,
	0x2e, 0x76, 0x31, 0x2e, 0x55, 0x70, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x20, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x1a, 0x12,
	0x18, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x71, 0x69, 0x6e, 0x69, 0x75, 0x2f, 0x76,
	0x31, 0x2f, 0x55, 0x70, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x83, 0x01, 0x0a, 0x0e, 0x55, 0x70,
	0x6c, 0x6f, 0x61, 0x64, 0x46, 0x69, 0x6c, 0x65, 0x42, 0x61, 0x73, 0x65, 0x12, 0x24, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x75, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x2e, 0x76, 0x31, 0x2e, 0x55, 0x70, 0x6c,
	0x6f, 0x61, 0x64, 0x46, 0x69, 0x6c, 0x65, 0x42, 0x61, 0x73, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x22, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x75, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x2e,
	0x76, 0x31, 0x2e, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x46, 0x69, 0x6c, 0x65, 0x42, 0x61, 0x73,
	0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x27, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x21, 0x3a, 0x01,
	0x2a, 0x22, 0x1c, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x71, 0x69, 0x6e, 0x69, 0x75,
	0x2f, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x46, 0x69, 0x6c, 0x65, 0x42, 0x61, 0x73, 0x65, 0x42,
	0x42, 0x0a, 0x0d, 0x61, 0x70, 0x69, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x76, 0x31,
	0x50, 0x01, 0x5a, 0x2f, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6d,
	0x65, 0x64, 0x74, 0x72, 0x69, 0x62, 0x2f, 0x68, 0x61, 0x6f, 0x6a, 0x69, 0x73, 0x68, 0x75, 0x2d,
	0x70, 0x62, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x76, 0x31,
	0x3b, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_common_v1_qiniu_proto_rawDescOnce sync.Once
	file_common_v1_qiniu_proto_rawDescData = file_common_v1_qiniu_proto_rawDesc
)

func file_common_v1_qiniu_proto_rawDescGZIP() []byte {
	file_common_v1_qiniu_proto_rawDescOnce.Do(func() {
		file_common_v1_qiniu_proto_rawDescData = protoimpl.X.CompressGZIP(file_common_v1_qiniu_proto_rawDescData)
	})
	return file_common_v1_qiniu_proto_rawDescData
}

var file_common_v1_qiniu_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_common_v1_qiniu_proto_goTypes = []interface{}{
	(*UpTokenRequest)(nil),        // 0: api.upload.v1.UpTokenRequest
	(*UpTokenRequestReply)(nil),   // 1: api.upload.v1.UpTokenRequestReply
	(*UploadFileBaseRequest)(nil), // 2: api.upload.v1.UploadFileBaseRequest
	(*UploadFileBaseReply)(nil),   // 3: api.upload.v1.UploadFileBaseReply
}
var file_common_v1_qiniu_proto_depIdxs = []int32{
	0, // 0: api.upload.v1.QiNiu.UpToken:input_type -> api.upload.v1.UpTokenRequest
	2, // 1: api.upload.v1.QiNiu.UploadFileBase:input_type -> api.upload.v1.UploadFileBaseRequest
	1, // 2: api.upload.v1.QiNiu.UpToken:output_type -> api.upload.v1.UpTokenRequestReply
	3, // 3: api.upload.v1.QiNiu.UploadFileBase:output_type -> api.upload.v1.UploadFileBaseReply
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_common_v1_qiniu_proto_init() }
func file_common_v1_qiniu_proto_init() {
	if File_common_v1_qiniu_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_common_v1_qiniu_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpTokenRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_v1_qiniu_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpTokenRequestReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_v1_qiniu_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UploadFileBaseRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_v1_qiniu_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UploadFileBaseReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_common_v1_qiniu_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_common_v1_qiniu_proto_goTypes,
		DependencyIndexes: file_common_v1_qiniu_proto_depIdxs,
		MessageInfos:      file_common_v1_qiniu_proto_msgTypes,
	}.Build()
	File_common_v1_qiniu_proto = out.File
	file_common_v1_qiniu_proto_rawDesc = nil
	file_common_v1_qiniu_proto_goTypes = nil
	file_common_v1_qiniu_proto_depIdxs = nil
}
