// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: api/common/v1/query.proto

package v1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on GetCountryIsoRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetCountryIsoRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetCountryIsoRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetCountryIsoRequestMultiError, or nil if none found.
func (m *GetCountryIsoRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *GetCountryIsoRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if ip := net.ParseIP(m.GetIp()); ip == nil {
		err := GetCountryIsoRequestValidationError{
			field:  "Ip",
			reason: "value must be a valid IP address",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return GetCountryIsoRequestMultiError(errors)
	}

	return nil
}

// GetCountryIsoRequestMultiError is an error wrapping multiple validation
// errors returned by GetCountryIsoRequest.ValidateAll() if the designated
// constraints aren't met.
type GetCountryIsoRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetCountryIsoRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetCountryIsoRequestMultiError) AllErrors() []error { return m }

// GetCountryIsoRequestValidationError is the validation error returned by
// GetCountryIsoRequest.Validate if the designated constraints aren't met.
type GetCountryIsoRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetCountryIsoRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetCountryIsoRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetCountryIsoRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetCountryIsoRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetCountryIsoRequestValidationError) ErrorName() string {
	return "GetCountryIsoRequestValidationError"
}

// Error satisfies the builtin error interface
func (e GetCountryIsoRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetCountryIsoRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetCountryIsoRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetCountryIsoRequestValidationError{}

// Validate checks the field values on GetCountryIsoReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetCountryIsoReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetCountryIsoReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetCountryIsoReplyMultiError, or nil if none found.
func (m *GetCountryIsoReply) ValidateAll() error {
	return m.validate(true)
}

func (m *GetCountryIsoReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Ios

	if len(errors) > 0 {
		return GetCountryIsoReplyMultiError(errors)
	}

	return nil
}

// GetCountryIsoReplyMultiError is an error wrapping multiple validation errors
// returned by GetCountryIsoReply.ValidateAll() if the designated constraints
// aren't met.
type GetCountryIsoReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetCountryIsoReplyMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetCountryIsoReplyMultiError) AllErrors() []error { return m }

// GetCountryIsoReplyValidationError is the validation error returned by
// GetCountryIsoReply.Validate if the designated constraints aren't met.
type GetCountryIsoReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetCountryIsoReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetCountryIsoReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetCountryIsoReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetCountryIsoReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetCountryIsoReplyValidationError) ErrorName() string {
	return "GetCountryIsoReplyValidationError"
}

// Error satisfies the builtin error interface
func (e GetCountryIsoReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetCountryIsoReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetCountryIsoReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetCountryIsoReplyValidationError{}
